FROM composer as builder
WORKDIR /app
COPY composer.* ./
RUN composer install --no-scripts

FROM php:8.3-fpm-alpine as build
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod 755 /usr/local/bin/install-php-extensions

RUN install-php-extensions gd pgsql pdo_pgsql amqp

WORKDIR /app

FROM build as dev
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
RUN install-php-extensions xdebug-3.3.2
FROM build as prod

COPY docker/php/php.ini /usr/local/etc/php/php.ini
COPY docker/php/www.conf /usr/local/etc/php/www.conf

COPY --from=builder /app/vendor /app/vendor
COPY ./ ./

RUN chown -R www-data:www-data /app



