framework:
    messenger:
        default_bus: default
        buses:
            default:
                default_middleware:
                    allow_no_handlers: true

        transports:
            sync: 'sync://'

        routing:
            # Route your messages to the transports
#            Ticketing\Common\IntegrationEvent\IntegrationEventInterface: distributed
