<?php

namespace App\Tests\Integration;

use Faker\Factory;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

abstract class AbstractIntegrationTestCase extends KernelTestCase
{
    protected \Faker\Generator $faker;

    protected function setUp(): void
    {
        $this->faker = Factory::create();
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
