name: Deploy to dev env
on:
    push:
        branches:
            - dev
env:
    PROJECT_FOLDER: /var/www/dev.ticketing
jobs:
    test:
         uses: ./.github/workflows/test.yml
         secrets:
             DOCKER_USER: ${{ secrets.DOCKER_USER }}
             DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    build:
        needs: test
        uses: ./.github/workflows/build.yml
        with:
            image-tag: dev
            image-php-target: dev
        secrets:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Prepare deployment-compose file
                run: mv docker-compose.deployment.yaml docker-compose.tickets.yaml
            -   name: copy file via ssh password
                uses: appleboy/scp-action@v0.1.7
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USERNAME }}
                    key: ${{ secrets.SERVER_KEY }}
                    source: 'docker-compose.tickets.yaml'
                    target: '${{ env.PROJECT_FOLDER }}/docker'
            -   name: ssh key passphrase
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USERNAME }}
                    key: ${{ secrets.SERVER_KEY }}
                    debug: true
                    script: |
                        cd ${{ env.PROJECT_FOLDER }}
                        docker image pull dzhuryn/ticketing-tickets-webserver:dev
                        docker image pull dzhuryn/ticketing-tickets-php:dev
                        docker image pull dzhuryn/ticketing-tickets-jobber:dev
                        docker-compose down gateway
                        docker-compose up -d 
                        docker-compose exec tickets_php bin/console doctrine:migrations:migrate --no-interaction
