name: Deploy to dev env
on:
    push:
        branches:
            - dev
jobs:
    test:
         uses: ./.github/workflows/test.yml
         secrets:
             DOCKER_USER: ${{ secrets.DOCKER_USER }}
             DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    build:
        needs: test
        uses: ./.github/workflows/build.yml
        with:
            image-tag: dev
            image-php-target: dev
        secrets:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: ssh key passphrase
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USERNAME }}
                    key: ${{ secrets.SERVER_KEY }}
                    debug: true
                    script: |
                        cd /var/www/dev.ticketing
                        docker-compose pull
                        docker-compose down gateway
                        docker-compose up -d 
                        docker-compose exec tickets_php bin/console doctrine:migrations:migrate --no-interaction
